#!/usr/bin/env bash
# Installs Nginx and configures the root page to return "Holberton School"

# Exit if any command fails
set -e

# Install nginx
apt update
apt install -y nginx

# Replace default page with required text
echo "Holberton School" > /var/www/html/index.html

# Start nginx without systemctl
if command -v service >/dev/null 2>&1; then
    service nginx restart
else
    /etc/init.d/nginx restart
fi
