#!/usr/bin/env bash
# Install Nginx package and dependencies

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/# listen 80/listen 80/' /etc/nginx/sites-available/default

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
