#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add the redirect for /redirect_me in Nginx config
sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 /;\n\t}' /etc/nginx/sites-available/default

# Add homepage content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx to apply the changes
sudo service nginx restart
